export interface IDealerInformationState
{
    CallRecordNumber:string;
    Date:string;
    Taker:string;
    DealerName:string;
    DealerContact:string;
    EmailAddress:string;
    Machine:string;
    MachineSN:string;
    Customer:string;
    LinkageInterface:string;
    Width:string;
    Capacity:string;
    WorkToolProductFamily:string;
    Get:string;
    OrderInformation:string;
    Quote:string;
    DiscPer:string;
}